#配置端口号
server:
  port: 8089
#数据库相关配置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gym_system?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8
    username: root
    password: root
  servlet:
    multipart:
      max-file-size: 200MB  #设置单个文件的大小  因为springboot内置tomact的的文件传输默认为10MB
      max-request-size: 500MB   #设置单次请求的文件总大小
      enabled: true    #千万注意要设置该参数，否则不生效
# minio配置
minio:
  endpoint: http://127.0.0.1:9000
  accesskey: minioadmin
  secretKey: minioadmin
#mybaits-plus配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #将日志信息输出到控制台
    map-underscore-to-camel-case: true #开启自动驼峰转换
  global-config:
    db-config:
      update-strategy: not_empty #只更新非空和非null的

#定义日志输出格式
logging:
  pattern:
    console: '%clr(%d{yyyy-MM-dd}){faded} [%thread] %clr(%-5level){green} %clr(%logger){cyan}- %clr(%msg){default}%n'